# docker-compose.yml
version: '3.8'
services:
  llm-agent:
    build: .
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - VL_LLM_MODEL_NAME=${VL_LLM_MODEL_NAME}
      - ASR_MODEL_NAME=${ASR_MODEL_NAME}
      - MODEL_LOADING_STRATEGY=${MODEL_LOADING_STRATEGY}
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8000:8000"
    volumes:
      - model-cache:/root/.cache/huggingface
    runtime: nvidia

volumes:
  model-cache:
    driver: local