# docker-compose.yml
version: '3.8'
services:
  llm-agent:
    # Usar la imagen descargada desde GHCR
    image: ghcr.io/dfedez920912/agente-llm-multimodal:main # O la etiqueta que subiste
    # build: . # <-- Comentar o eliminar esta línea
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - VL_LLM_MODEL_NAME=${VL_LLM_MODEL_NAME}
      - ASR_MODEL_NAME=${ASR_MODEL_NAME}
      - TTS_MODEL_NAME=${TTS_MODEL_NAME} # Si aplica
      - MODEL_LOADING_STRATEGY=${MODEL_LOADING_STRATEGY}
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN} # <-- Añadir esta línea
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8000:8000"
    volumes:
      - model-cache:/root/.cache/huggingface
    runtime: nvidia # <-- Reemplazar 'deploy' por esta línea
    # environment: # <-- Eliminar esta sección si existe
    #   - NVIDIA_VISIBLE_DEVICES=all

volumes:
  model-cache:
    driver: local